language: java

jdk:
  - openjdk17

cache:
  directories:
    - '$HOME/.m2/repository'

script:
  - ./gradlew clean package > /dev/null

install: ./gradlew clean shadowJar > /dev/null

after_success:
  - bash <(curl -s https://codecov.io/bash) -t a704ca30-58ab-4460-862c-7ebc63d0a097
