defaultName: athena

server:
  minThreads: 20
  maxThreads: 250
  applicationConnectors:
  - type: http
    port: 8080
  adminConnectors:
  - type: http
    port: 8081

swagger:
  resourcePackage: org.athena.api.resource
  title: Athena API
  version: 1.0
  enabled: true
  schemes:
    - http

snowflake:
  workerId: 0
  dataCenterId: 0

# 测试配置，线上使用 nginx配置
cors:
  allowedOrigins: '*'
  allowedMethods: OPTIONS, GET, PUT, PATCH, POST, DELETE, HEAD
  allowedHeaders: DNT, User-Agent, X-Requested-With, If-Modified-Since, Cache-Control, Content-Type, Range, Authorization
  urlPatterns:
    - /*

# Logging settings.
logging:
  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO
  # Logger-specific levels.
  loggers:
    # Overrides the level of com.example.dw.Thing and sets it to DEBUG.
    # "com.example.dw.Thing": DEBUG
    "org.reflections":
      level: OFF

database:
  driverClass: org.postgresql.Driver
  user: test
  password: 123456
  url: jdbc:postgresql://localhost:5432/test
  properties:
    charSet: UTF-8
  maxWaitForConnection: 1s
  validationQuery: "/* MyService Health Check */ SELECT 1"
  minSize: 10
  maxSize: 100
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute

redis:
  address: redis://localhost:6379
  password: 123456
  db: 8

elasticsearch:
  hostname: localhost
  port: 9200
  scheme: http
